######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 12 07:18:23 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += block.h game.h
SOURCES += block.cpp game.cpp main.cpp
