######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 23 04:24:01 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += randomized_queue.h
SOURCES += main_rand.cpp
