######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 8 13:27:09 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += brute.h fast.h point.h pointplotter.h
SOURCES += brute.cpp fast.cpp main.cpp point.cpp pointplotter.cpp
