######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 22 23:44:35 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += deque.h
SOURCES += main_deque.cpp
